baseurl = "https://aazim-yaswant.github.io"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Pwn-Eat-Sleep-Repeat"
theme = "beautifulhugo"
publishDir = "docs"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "subrat-sahu.github.io"
#googleAnalytics = "XXX"

[Params]
  subtitle = "A Blog of an Information Security Enthusiast!"
  logo = "img/avatar-icon.jpg"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2017"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/triangle.jpg"
  desc = "Triangle"
[[Params.bigimg]]
  src = "img/sphere.jpg"
  desc = "Sphere"
[[Params.bigimg]]
  src = "img/hexagon.jpg"
  desc = "Hexagon"

[Author]
  name = "Aazim Bill SE Yaswant"
  website = "aazim-yaswant.github.io"
  email = "aazimcr@gmail.com"
  facebook = "username"
  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "aazim-yaswant"
  #gitlab = "username"
  twitter = "username"
  #reddit = "username"
  linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3


[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
